AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaName:
    Default: "default-function-name"
    Description: "Function lambda name"
    Type: String
    MinLength: "1"
    MaxLength: "100"
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*

Resources:

    FunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Join [ "-", [ !Ref LambdaName, "role" ] ]
        AssumeRolePolicyDocument: 
          Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
             - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          
    FunctionLogs:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Join [ "-", [ !Ref LambdaName, "logs" ] ]

    Function:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Ref LambdaName
        Handler: app.index.main
        Code:
          ZipFile: |
            # this code will be replaced after, it is just to create de lambda function
            def main(event, context):
              print("empty lambda function")
        Role: !GetAtt FunctionRole.Arn
        Runtime: python3.10
        LoggingConfig:
          LogGroup: !Ref FunctionLogs
          LogFormat: Text
  
    CronExecutionRule:
      Type: AWS::Events::Rule
      Properties:
        Name: !Join [ "-", [ !Ref LambdaName, "execution-rule" ] ]
        ScheduleExpression: "cron(*/2 * * * ? *)"
        State: ENABLED
        Targets:
          - Id: !Join [ "-", [ !Ref LambdaName, "rule-target" ] ]
            Arn: !GetAtt Function.Arn
    
    CronExecutionRulePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName: !GetAtt Function.Arn
        Principal: "events.amazonaws.com"
        SourceArn: !GetAtt CronExecutionRule.Arn
       